### ISSUE TITLE
it cannot find the class jar.And I import right the way.

### ISSUE THREAD

**Issue by alemic** [itsrts/pptviewer-android#1]
Dear sir,

it cannot find the class jar.And I import right the way.

11-16 05:14:48.651: E/dalvikvm(15960): Could not find class 'com.itsrts.pptviewer.PPTViewer', referenced from method com.cat.activity.VipPptDetailActivity.onAfterSetContentView
11-16 05:14:48.651: W/dalvikvm(15960): VFY: unable to resolve check-cast 900 (Lcom/itsrts/pptviewer/PPTViewer;) in Lcom/cat/activity/VipPptDetailActivity;
11-16 05:14:48.661: W/dalvikvm(15960): Unable to match class for part: 'Lcom/itsrts/pptviewer/PPTViewer;'
11-16 05:14:48.661: W/dalvikvm(15960): threadid=1: thread exiting with uncaught exception (group=0x41369438)

**Comment by itsrts** [comment]
Hi, alemic,
I would like to know which IDE are you using.
if you are using eclipse, you need to paste the jar file in your libs folder.
After that, try to write the following code in your XML file :
< com.itsrts.pptviewer.PPTViewer
android:id="@+id/pptviewer"
android:width="match_parent"
android:height="match_parent"
/>
In the graphical layout yo should see the layout.
If not then some thing is not going good with the build path...try fixing them

or you can mail me at

rextechnosolutions@gmail.com
