### ISSUE TITLE
generating release apk occur mistake

### ISSUE THREAD

**Issue by foreverGoUp** [itsrts/pptviewer-android#10]
Warning:Exception while processing task java.io.IOException: Can't read [E:\ASWorkSpace\Label\app\libs\itsrts-pptviewer.jar(;;;;;;**/*.class)] (Can't process class [com/olivephone/office/a/b/e/p.class] (Unknown verification type [17] in stack map frame))

i need unProguarded jar,thx.could you replace old or add one in your github here and declare the new jar,thx.

**Comment by ah-dev-med** [comment]
facing same issue .. any updates regrading it.

**Comment by itsrts** [comment]
Can't help regarding this.
