### ISSUE TITLE
I got an error, please help me out.

### ISSUE THREAD

**Issue by soumente** [itsrts/pptviewer-android#15]
Hi, I am using your library for showing ppt files inside my application. But recently we enabled multdex for the project. When i build the project i get this error.

Error:Execution failed for task 'App:transformClassesWithMultidexlistForDevDebug'.

java.io.IOException: Can't read [C:\Projects\Android\build\intermediates\transforms\jarMerging\dev\debug\jars\1\1f\combined.jar](Can't process class [com/olivephone/office/a/b/e/p.class] %28Unknown verification type [17] in stack map frame%29)

i found that the jar file placed inside the libs folder is the source of this issue. Could you send me the source code so we can make it as a library project and fix this issue.

We are stuck in this problem. Waiting for your response

My email address : soumen.adhikari@technoexponent.com

Thanks in advance
Soumen Adhikari

**Comment by itsrts** [comment]
I've stopped maintaining the project, can't help
