### ISSUE TITLE
请求将项目中用到的库开源

### ISSUE THREAD

**Issue by JerryLocke** [itsrts/pptviewer-android#2]
找了很久，也没有找到一个完美的解决方案。
直到找到本项目，终于能够将PPT展示出来显示，但其中的库是加密混淆的。
这个库提供的功能实在有限，我想要进行定制化，所以能不能将其开源？
感谢！

**Comment by itsrts** [comment]
Sorry my friend, the library is not available as open source.

2015-08-06 11:32 GMT+05:30 Jerry Locke notifications@github.com:

**Comment by itsrts** [comment]
Although, you can customize the zoom image and other sort of things for
customizing the ui but not the functionality

2015-08-06 12:43 GMT+05:30 Rex Techno rextechnosolutions@gmail.com:

**Comment by JerryLocke** [comment]
So, would you please do some simple modifications to the library? If you can, please provide the following methods:
1. void setPageNumEnabled(boolean enabled) : to disable or enable the page num.
2. void setSlidePromptEnabled(boolean enabled) : to disable or enable the toast in first side and last side.
3. Bitmap getCurrentSlideSnapshot() : to get snapshot of the current slide.
4. void next() : to switch to next slide.
5. void previous() : to switch to previous slide.
I'm doing a non-commercial project, and this will determine whether or not I can get good results in the match.I hope you can help me.
Thanks a lot.

**Comment by itsrts** [comment]
Sure, plz give me some time I will revert back to you.

**Comment by JerryLocke** [comment]
THX. :-D

**Comment by JerryLocke** [comment]
I'm sorry to bother you again.
But the match will start in the day after tomorrow, and I have no more time.
So would you please hurry up to complete? 
Thanks a lot.
