### ISSUE TITLE
License for PPTView-Android ?

### ISSUE THREAD

**Issue by pokoso** [itsrts/pptviewer-android#21]
Hello Rajdeep

Could you please let me know the licensing policy of the solution?

Thank you.

**Comment by pokoso** [comment]
I found the SDK at 'https://www.olivephone.com/index.html'.
And I think the license depends on it.

**Comment by itsrts** [comment]
Yes, the base library is olivephone but the free version of it, so it depends on their free version policy.
Please read through their current policy. I'm no longer actively maintaining this project.
