### ISSUE TITLE
PPTViewer stuck at loading!

### ISSUE THREAD

**Issue by hamzakhurshid12** [itsrts/pptviewer-android#22]
I am using the library in my android project for API 28. After loading the ppt file into the widget, I only see the loading screen and it keeps on loading forever. The file doesn't load. 

The same issue has been explained and is unanswered on StackOverflow at https://stackoverflow.com/questions/48445529/load-ppt-file-using-third-party-android-library

**Comment by hamzakhurshid12** [comment]
Problem Solved. I was trying to open latest powerpoint extension (PPTX). I figured that the library doesn't support it. It only support PPTX files.

**Comment by aryan00018** [comment]
May you please tell me how you solved this particular issue because I am also facing the same issue....its urgent....I used both pptx and ppt format.
