### ISSUE TITLE
Support for AndroidX

### ISSUE THREAD

**Issue by gstephin** [itsrts/pptviewer-android#23]
I'm using androidx in my project, i got the below error while integrating the lib 

Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Failed to transform file 'itsrts-pptviewer.jar' to match attributes {artifactType=android-classes, org.gradle.usage=java-runtime-jars}
      > Execution failed for JetifyTransform: D:\Development\Baashaa Enterprise\Enterprise\app\libs\itsrts-pptviewer.jar.
         > Failed to transform 'D:\Development\Baashaa Enterprise\Enterprise\app\libs\itsrts-pptviewer.jar' using Jetifier. R

**Comment by SamraMehboob** [comment]
Hi..
Dud you manage to find the solution how to use this libarary with Androidx?

**Comment by itsrts** [comment]
Further development and support is not provided for this project
