### ISSUE TITLE
Can you give me the source code of itsrts-pptviewer.jar?

### ISSUE THREAD

**Issue by lbb1993** [itsrts/pptviewer-android#6]
hello!
Iwant to control the time for each ppt page,but I don't find the way to do this.Can you give me the source code of itsrts-pptviewer.jar? My email is 279173135@qq.com. thank you very much!

**Comment by arlm** [comment]
If possible I would like that too.

Thanks.

**Comment by JayakrishnanPmWC** [comment]
Hi, I am using your library for showing ppt files inside my application. But recently we enabled multdex for the project. When i build the project i get this error.

Error:Execution failed for task 'App:transformClassesWithMultidexlistForDevDebug'.

> java.io.IOException: Can't read [C:\Projects\Android\build\intermediates\transforms\jarMerging\dev\debug\jars\1\1f\combined.jar](Can't process class [com/olivephone/office/a/b/e/p.class] %28Unknown verification type [17] in stack map frame%29)

i found that the jar file placed inside the libs folder is the source of this issue. Could you send me the source code so we can make it as a library project and fix this issue.

We are stuck in this problem. Waiting for your response

My email address :  jk@webandcrafts.com

Thanks in advance
Jayakrishnan PM

**Comment by rishabhMaltare** [comment]
@JayakrishnanPmWC  Same issue here. Have you found any solution yet?

**Comment by akashKite** [comment]
Hello,
Which type of problems you are getting?

**Comment by rishabhMaltare** [comment]
Error:Execution failed for task 'App:transformClassesWithMultidexlistForDevDebug'.

java.io.IOException: Can't read [C:\Projects\Android\build\intermediates\transforms\jarMerging\dev\debug\jars\1\1f\combined.jar](Can't process class [com/olivephone/office/a/b/e/p.class] %28Unknown verification type [17] in stack map frame%29)

**Comment by daidaifujun** [comment]
If possible！I also need source code of itsrts-pptviewer.jar！
My email address :171355744@qq.com

**Comment by windhuiyi** [comment]
Can you give me the itsrts-pptviewer source code? I want to know how it work and custom it.Thank you!~ My email address is tonglei54@gmail.com.

**Comment by Nikhil1999** [comment]
If possible！I also need source code of itsrts-pptviewer.jar!
My email address : nikhilkoshty@gmail.com

**Comment by S26T** [comment]
If possible！I also need source code of itsrts-pptviewer.jar!
My email address : grekstar26@gmail.com

**Comment by james-smith-javaman** [comment]
If possible！I also need source code of itsrts-pptviewer.jar!
My email address : james.smith.javaman@gmail.com
Thanks!

**Comment by arvindkkore** [comment]
I also need source code of itsrts-pptviewer.jar, As I am getting  same error while using this lib  with aspose  libraries
My email address :kore.arvind@gmail.com
Thanks!

**Comment by vivekgotraj** [comment]
If possible！I also need source code of itsrts-pptviewer.jar!
My email address : vpgogenks@gmail.com
Thanks

**Comment by amrutbidri** [comment]
If possible！I also need source code of itsrts-pptviewer.jar!
My email address : amrutbidri@gmail.com
Thanks!

**Comment by ChandsiGupta** [comment]
If possible！I also need source code of itsrts-pptviewer.jar!
My email address : guptachandsi1994@gmail.com
Thanks!

**Comment by cemalaytekin** [comment]
If possible！I also need source code of itsrts-pptviewer.jar!
My email address : cemalaytekinnn@gmail.com
Thanks!

**Comment by FE-FadyEmad** [comment]
Hi, I am using your library for showing ppt files inside my application. But  there is a problem while trying to generate signedAPK with proguard for itsrts-pptviewer.jar
If possible！I also need the source code of itsrts-pptviewer.jar!
My email address: fe.fady.emad@gmail.com
Thanks!

**Comment by dmitrybilko** [comment]
Please, provide the sources for me as well. dmitry.bilko@danavero.com

**Comment by MHassanIqbal** [comment]
Please, provide the sources for me as well. mhassaniqbal22@gmail.com

**Comment by alfirin** [comment]
Hello, 

Thanks for this library.
Is-it possible to have the source too ?

Thanks a lot dude.
Here is my email : jimmy.grand@turacoo.com

**Comment by Saad46464** [comment]
If possible！I also need source code of itsrts-pptviewer.jar！
My email address :saadmughal4646@gmail.com

**Comment by Saad46464** [comment]
i am not able to edit .jar find error source missing please help

**Comment by vihangayw** [comment]
If possible！ Please send the source to jar
My email address : vyasith@gmail.com

**Comment by ahmadarslan13** [comment]
If possible！ Please send the source to jar
My email address : arslanahmad301@gmail.com

**Comment by saad1412** [comment]
If possible！ Please send the source to jar
My email address : saadahmad1214@gmail.com

**Comment by michael-xiao** [comment]
If possible！ Please send the source to jar
My email address : 838230011@qq.com

**Comment by keepmovng** [comment]
If possible！ Please send the source to jar
My email address : sucaide@star-net.cn

**Comment by lxgonyx** [comment]
Hello,
If possible！ I also need source code of itsrts-pptviewer.jar!

Thanks a lot.

My email address : lxg@onyx-international.com

**Comment by itsrts** [comment]
Source Code is not available, please manipulate the UI via JAVA code

**Comment by zeper2001** [comment]
What is the license? Is it an Apache license?

**Comment by jacob-abe** [comment]
Anyways OP whats the reason for the secrecy with the source code, is that due to an NDA?

**Comment by faisalasif180** [comment]
If possible！ Please send the source to jar
My email address : [f6494180@gmail.com)

**Comment by luncang** [comment]
if possible, could you please send the source of the jar? Thank you.
My email: lc1031012395@gmail.com
